cc_library(
    name = "DelegatingCalls2RealObject",
    hdrs = [
        "MockRealObject.h",
        "RealObject.h",
    ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)