cc_library(
    name = "PacketStream",
    hdrs = [
        "ConcretePacketStream.h",
        "UsePacketStream.h",
        "MockPacketStream.h"
    ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)