cc_library(
    name = "PacketStream",
    hdrs = [
        "ConcretePacketStream.h",
        "UsePacketStream.h"
    ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)