cc_library(
    name = "Matcher",
    hdrs = [
        "FooO.h",
        "MockFooO.h",
        "TypeForMatcher.h"
    ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)