cc_library(
    name = "gtest_lib",
    srcs = [
        "gtest/libgmock_main.a",
        "gtest/libgmock.a",
        "gtest/libgtest_main.a",
        "gtest/libgtest.a",
        ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)