cc_library(
    name = "gtest_lib",
    srcs = [
        "gtest/**/*.h",
        "gmock/**/*.hpp",
        "include/**/*.inl",
        ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)